# Assignment-3

This notebook contains the coding questions to test the proficiency in `Pandas` library in python.

### Date: 13th December, 2025

### Steps to solve and upload the assignment 

- Download the notebook in your local machine.
- Solve the questions in the notebook and save it.
- Rename the file as `Assignment-03-<your_name>_<your_surname>.ipynb`. For example if your name is Dipika Chopra then name the file as `Assignment-03-Dipika_Chopra.ipynb`.
- Upload the solved notebook in your github repo under the folder **Assignment-3**.
- Upload the solved notebook in the google drive location: https://drive.google.com/drive/folders/1mMtPeHCmsKQE8KxK_RmnFFkTPfo5RYNJ?usp=drive_link 
<h3><span style="color:red"> Deadline: 10th January, 2026 </span></h3>

Use the `population_by_county.csv` file in the folder to complete the tasks.

**NOTE: TRY TO DO ALL THE TASKS IN ONE LINE OF PANDAS CODE.**

In [ ]:
import pandas as pd

#### 1. Import pandas and read in the `population_by_county.csv` file into a dataframe called `pop`.

In [28]:
# Write your code here

import pandas as pd

# Read the CSV file into a dataframe
try:
    pop = pd.read_csv('population_by_county.csv')
    print("DataFrame 'pop' created successfully:")
    # You can add a line to print the head of the dataframe to verify it loaded correctly, e.g.:
    print(pop.head(8))
    print(pop.head().columns) 

    print(pop['State'].unique())
    print(pop['State'].value_counts())
except FileNotFoundError:
    print("Error: The file 'population_by_county.csv' was not found.")
except Exception as e:
    print(f"An error occurred: {e}")

DataFrame 'pop' created successfully:
             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054
5      Adair County        Kentucky       18656            19485
6      Adair County        Missouri       25607            25377
7      Adair County        Oklahoma       22683            21909
Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='object')
['South Carolina' 'Louisiana' 'Virginia' 'Idaho' 'Iowa' 'Kentucky'
 'Missouri' 'Oklahoma' 'Colorado' 'Illinois' 'Indiana' 'Mississippi'
 'Nebraska' 'North Dakota' 'Ohio' 'Pennsylvania' 'Washington' 'Wisconsin'
 'Vermont' 'Minnesota' 'Florida' 'North Carolina' 'California' 'New York'
 'Wyoming' 'Michigan' 'Alaska' 'Maryland' 'Kansas' 'Tennessee' 'Texas'
 'Maine' 'Arizona' 'Georgia' 'Arkansas' 'New Jersey' 'South Dakota'
 'Alabama' 'Oregon' 'West Virginia' 'Massachusetts' 'Utah' 'Montana'
 'New Hampshire' 'New Mexico' 'Rhode Island' 'Nevada'
 'District of Columbia' 'Connecticut' 'Hawaii' 'Delaware']
State
Texas                   254
Georgia                 159
Virginia                133
Kentucky                120
Missouri                115
Kansas                  105
Illinois                102
North Carolina          100
Iowa                     99
Tennessee                95
Nebraska                 93
Indiana                  92
Ohio                     88
Minnesota                87
Michigan                 83
Mississippi              82
Oklahoma                 77
Arkansas                 75
Wisconsin                72
Florida                  67
Alabama                  67
Pennsylvania             67
South Dakota             66
Louisiana                64
Colorado                 64
New York                 62
California               58
Montana                  56
West Virginia            55
North Dakota             53
South Carolina           46
Idaho                    44
Washington               39
Oregon                   36
New Mexico               33
Utah                     29
Alaska                   29
Maryland                 24
Wyoming                  23
New Jersey               21
Nevada                   17
Maine                    16
Arizona                  15
Vermont                  14
Massachusetts            14
New Hampshire            10
Connecticut               8
Rhode Island              5
Hawaii                    5
Delaware                  3
District of Columbia      1
Name: count, dtype: int64

#### 2. Show the head of the dataframe, Also show top 8 rows of the dataframe using head

In [5]:
# Write your code here

import pandas as pd
    # first 5 rows
pop.head(8)    # first 8 rows

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054
5      Adair County        Kentucky       18656            19485
6      Adair County        Missouri       25607            25377
7      Adair County        Oklahoma       22683            21909

#### 3. What are the column names?

In [6]:
# Write your code here

column1  = pop.columns
print(column1)

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='object')

#### 4. How many States are represented in this data set?  
<em>Note: the data includes the `District of Columbia`</em>

In [10]:
# Write your code here

# pop.nunique()
pop['State'].unique()
pop['State'].value_counts()

State
Texas                   254
Georgia                 159
Virginia                133
Kentucky                120
Missouri                115
Kansas                  105
Illinois                102
North Carolina          100
Iowa                     99
Tennessee                95
Nebraska                 93
Indiana                  92
Ohio                     88
Minnesota                87
Michigan                 83
Mississippi              82
Oklahoma                 77
Arkansas                 75
Wisconsin                72
Florida                  67
Alabama                  67
Pennsylvania             67
South Dakota             66
Louisiana                64
Colorado                 64
New York                 62
California               58
Montana                  56
West Virginia            55
North Dakota             53
South Carolina           46
Idaho                    44
Washington               39
Oregon                   36
New Mexico               33
Utah                     29
Alaska                   29
Maryland                 24
Wyoming                  23
New Jersey               21
Nevada                   17
Maine                    16
Arizona                  15
Vermont                  14
Massachusetts            14
New Hampshire            10
Connecticut               8
Rhode Island              5
Hawaii                    5
Delaware                  3
District of Columbia      1
Name: count, dtype: int64

#### 5. Get a list or array of all the states in the data set.

In [11]:
# Write your code here

pop['State'].value_counts()

pop['State'].unique().tolist()

['South Carolina',
 'Louisiana',
 'Virginia',
 'Idaho',
 'Iowa',
 'Kentucky',
 'Missouri',
 'Oklahoma',
 'Colorado',
 'Illinois',
 'Indiana',
 'Mississippi',
 'Nebraska',
 'North Dakota',
 'Ohio',
 'Pennsylvania',
 'Washington',
 'Wisconsin',
 'Vermont',
 'Minnesota',
 'Florida',
 'North Carolina',
 'California',
 'New York',
 'Wyoming',
 'Michigan',
 'Alaska',
 'Maryland',
 'Kansas',
 'Tennessee',
 'Texas',
 'Maine',
 'Arizona',
 'Georgia',
 'Arkansas',
 'New Jersey',
 'South Dakota',
 'Alabama',
 'Oregon',
 'West Virginia',
 'Massachusetts',
 'Utah',
 'Montana',
 'New Hampshire',
 'New Mexico',
 'Rhode Island',
 'Nevada',
 'District of Columbia',
 'Connecticut',
 'Hawaii',
 'Delaware']

#### 6. What are the five most common County names in the U.S.?

In [ ]:
# Write your code here

pop['County'].value_counts().head(5)

pop['County'].value_counts().head(5).index.tolist()

['Washington County',
 'Jefferson County',
 'Franklin County',
 'Jackson County',
 'Lincoln County']

#### 7. What are the top 5 most populated Counties according to the 2010 Census?

In [22]:
# Write your code here

pop.groupby('County')['2010Census'].sum().sort_values(ascending=False).head(5)

County
Los Angeles County    9818605
Cook County           5217063
Orange County         4826896
Harris County         4124483
Maricopa County       3817117
Name: 2010Census, dtype: int64

#### 8. What are the top 5 most populated States according to the 2010 Census?

In [23]:
# Write your code here

pop.groupby('State')['2010Census'].sum().sort_values(ascending=False).head(5)

State
California    37253956
Texas         25145561
New York      19378102
Florida       18801310
Illinois      12830632
Name: 2010Census, dtype: int64

#### 9. How many Counties have 2010 populations greater than 1 million?

In [30]:
# Write your code here

pop[pop['2010Census'] > 1_000_000].shape[0]

39

#### 10. How many Counties don't have the word "County" in their name?

In [14]:
# Write your code here
(~pop['County'].str.contains('County', na=False)).sum()

np.int64(135)

#### 11. Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

In [18]:
# Write your code here

pop['Percent_Change_2010_2017'] = (
    (pop['2017PopEstimate'] - pop['2010Census'])
    / pop['2010Census']
) * 100

pop[['2010Census', '2017PopEstimate', 'Percent_Change_2010_2017']].head()

   2010Census  2017PopEstimate  Percent_Change_2010_2017
0       25417            24722                 -2.734390
1       61773            62590                  1.322584
2       33164            32545                 -1.866482
3      392365           456849                 16.434697
4        7682             7054                 -8.174954

#### 12. What States have the highest estimated percent change between the 2010 Census and the 2017 Population Estimate?

**NOTE:** This will take several lines of code, as it requires a recalculation of Percent Change.

In [22]:
# Write your code here
state_pop = pop.groupby('State')[['2010Census', '2017PopEstimate']].sum()

state_pop['Percent_Change_2010_2017'] = (
    (state_pop['2017PopEstimate'] - state_pop['2010Census'])
    / state_pop['2010Census']
) * 100

print(state_pop)
state_pop.sort_values('Percent_Change_2010_2017', ascending=False).head()

                      2010Census  2017PopEstimate  Percent_Change_2010_2017
State
Alabama                  4779736          4874747                  1.987788
Alaska                    710231           739795                  4.162589
Arizona                  6392017          7016270                  9.766135
Arkansas                 2915918          3004279                  3.030298
California              37253956         39536653                  6.127395
Colorado                 5029196          5607154                 11.492056
Connecticut              3574097          3588184                  0.394142
Delaware                  897934           961939                  7.128029
District of Columbia      601723           693972                 15.330808
Florida                 18801310         20984400                 11.611372
Georgia                  9687653         10429379                  7.656406
Hawaii                   1360301          1427538                  4.942803
Idaho                    1567582          1716943                  9.528114
Illinois                12830632         12802023                 -0.222974
Indiana                  6483802          6666818                  2.822665
Iowa                     3046355          3145711                  3.261471
Kansas                   2853118          2913123                  2.103138
Kentucky                 4339367          4454189                  2.646054
Louisiana                4533372          4684333                  3.329994
Maine                    1328361          1335907                  0.568068
Maryland                 5773552          6052177                  4.825885
Massachusetts            6547629          6859819                  4.767985
Michigan                 9883640          9962311                  0.795972
Minnesota                5303925          5576606                  5.141117
Mississippi              2967297          2984100                  0.566273
Missouri                 5988927          6113532                  2.080590
Montana                   989415          1050493                  6.173143
Nebraska                 1826341          1920076                  5.132393
Nevada                   2700551          2998039                 11.015826
New Hampshire            1316470          1342795                  1.999666
New Jersey               8791894          9005644                  2.431217
New Mexico               2059179          2088070                  1.403035
New York                19378102         19849399                  2.432111
North Carolina           9535483         10273419                  7.738842
North Dakota              672591           755393                 12.310899
Ohio                    11536504         11658609                  1.058423
Oklahoma                 3751351          3930864                  4.785289
Oregon                   3831074          4142776                  8.136152
Pennsylvania            12702379         12805537                  0.812116
Rhode Island             1052567          1059639                  0.671881
South Carolina           4625364          5024369                  8.626456
South Dakota              814180           869666                  6.814955
Tennessee                6346105          6715984                  5.828441
Texas                   25145561         28304596                 12.562993
Utah                     2763885          3101833                 12.227282
Vermont                   625741           623657                 -0.333045
Virginia                 8001024          8470020                  5.861700
Washington               6724540          7405743                 10.130106
West Virginia            1852994          1815857                 -2.004162
Wisconsin                5686986          5795483                  1.907812
Wyoming                   563626           579315                  2.783583

                      2010Census  2017PopEstimate  Percent_Change_2010_2017
State
District of Columbia      601723           693972                 15.330808
Texas                   25145561         28304596                 12.562993
North Dakota              672591           755393                 12.310899
Utah                     2763885          3101833                 12.227282
Florida                 18801310         20984400                 11.611372